# Generated by Django 4.0.2 on 2022-02-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=60)),
            ],
        ),
    ]
