# Generated by Django 4.0.2 on 2022-03-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_alter_participant_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
