# Generated by Django 4.0.2 on 2022-03-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='participant.teacher'),
        ),
    ]
